### ISSUE TITLE
Two problems with backend

### ISSUE THREAD

**Issue by carolynlphillips** [pdybka-ep/flask-todoapp#4]
As mentioned by the previous issue, deleting categories doesn't work and its for TWO reasons.

First, the logic to check if there are any todos attached to a category is wrong.  I redefined todos as

```
    todos=Todo.query.filter_by(category=category).first()
```

and now it works fine.

Second, the flash message doesn't work and throws an Internal Server error
flash('You have TODOs in that category. Remove them first.')

**Comment by pdybka-ep** [comment]
Sorry for the delay. Now everything should work fine.
